[buildPlans.punk-mono]
family = "Punk Mono"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = false

  [buildPlans.punk-mono.variants]
  inherits = "ss05"

    [buildPlans.punk-mono.variants.design]
    capital-b = "more-asymmetric-serifless"
    capital-g = "toothless-rounded-serifless-hooked"
    capital-i = "short-serifed"
    capital-k = "straight-serifless"
    capital-m = "hanging"
    capital-p = "open"
    capital-q = "crossing"
    capital-r = "straight-open"
    a = "double-storey-serifless"
    f = "flat-hook"
    g = "single-storey-flat-hook-serifless"
    i = "hooky"
    j = "serifed"
    k = "straight-top-left-serifed"
    l = "zshaped"
    m = "short-leg"
    q = "earless-corner-diagonal-tailed"
    r = "compact"
    s = "unilateral-serifed"
    t = "flat-hook-short-neck2"
    u = "motion-serifed"
    v = "straight-motion-serifed"
    w = "straight-motion-serifed"
    x = "straight-serifed"
    y = "straight"
    z = "straight-bottom-serifed"
    long-s = "flat-hook-tailed"
    lower-delta = "flat-top"
    capital-gamma = "top-right-serifed"
    lower-iota = "tailed-serifed"
    lower-lambda = "straight-turn"
    lower-xi = "rounded"
    cyrl-capital-ze = "unilateral-serifed"
    cyrl-ze = "bilateral-serifed"
    cyrl-capital-ka = "symmetric-touching-top-left-and-bottom-right-serifed"
    cyrl-ka = "symmetric-connected-serifed"
    cyrl-en = "serifed"
    cyrl-capital-u = "cursive"
    cyrl-capital-ya = "standing-open"
    cyrl-ya = "standing-open-tailed"
    cyrl-yeri = "round"
    cyrl-yery = "corner-tailed"
    zero = "dotted"
    one = "base"
    three = "flat-top"
    six = "open-contour"
    eight = "two-circles"
    nine = "straight-bar"
    paragraph-sign = "high"
    brace = "straight"
    ampersand = "upper-open"
    at = "fourfold-tall"
    dollar = "interrupted-cap"
    cent = "bar-interrupted"
    percent = "rings-segmented-slash"

  [buildPlans.punk-mono.ligations]
  inherits = "dlig"
